[package]
name = "cmus-notify"
version = "0.9.3"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2021"

[dependencies]
dirs = "5.0"
notify-rust = "4.0"

[dev-dependencies]
rstest = "0.17"
