name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies Ubuntu
        if: ${{contains(runner.os,'Linux')}}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libdbus-1-dev
      - name: Install Dependencies Mac
        if: ${{contains(runner.os,'macOS')}}
        run: |
          rustup component add rustfmt clippy --toolchain stable-x86_64-apple-darwin
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
# vim: ts=2 sw=2
